### ISSUE TITLE
生成的模型json中，不能显示继承父类的元素

### ISSUE THREAD

**Issue by lejie263** [apigcc/apigcc#14]
生成的模型json中，不能显示继承父类的元素

**Comment by lejie263** [comment]
public class RoleSelDto extends PageRequest {
    private Long roleId;
}

public class PageRequest {
   
    private int pageNum = 1;

    private int pageSize = 10;
}

![image](https://user-images.githubusercontent.com/21201229/49631649-c62b5100-fa2d-11e8-8704-beaa5b99fc25.png)

生成的请求中没有父类的属性

**Comment by ayz6uem** [comment]
apigcc能读到PageRequest的源码吗？

**Comment by ayz6uem** [comment]
如果PageRequest在第三方jar中，需要配置一下jar的路径，如果有源码，也可以配置一下源码路径

**Comment by lejie263** [comment]
好的，在一个jar包里面，我加下再看看。我先关了这个单子。多谢多谢！
另外提供建议，消息头参数，是否可以定制显示

**Comment by ayz6uem** [comment]
```
消息头参数，是否可以定制显示
```
比如？

**Comment by lejie263** [comment]
![image](https://user-images.githubusercontent.com/21201229/49634632-4ce52b80-fa38-11e8-9d4f-9d5d5807384f.png)

图片中我们是定义常量，不是直接写的参数key，所以生成文档也直接显示出来，是否定义个字典，进行替换。字典中有，就替换为字典的value，没有直接显示。

**Comment by ayz6uem** [comment]
好的，header这块儿的解析还需要再处理一下
