### ISSUE TITLE
什么原因能造成没有返回结果

### ISSUE THREAD

**Issue by nyjianjun** [apigcc/apigcc#16]
/**
     * 通过用户id查询用户详情
     * @param id 用户Id
     * @return UserVO
     */
    @PostMapping("find-user/{id}")
    public UserVO findUserById(@PathVariable long id) {
        UserVO userVO = new UserVO();
        userVO.setId(id);
        userVO.setAge(100);
        return userVO;
    }

UserVO 是使用lombok注解的

生成的结果 没有返回结果，只显示请求参数

**Comment by ayz6uem** [comment]
请问，问题是否解决了？

**Comment by horryw** [comment]
我们项目现在就有这个问题，请问要怎么解决呢
