### ISSUE TITLE
项目接口非常多，生成的html文档很大，有没有办法分组(注解)生成

### ISSUE THREAD

**Issue by scofier** [apigcc/apigcc#19]
我们的项目的接口非常多，没有分模块，导致生成的文档非常大，html有上百mb，可否分组生成文档？

分组可以考虑：
1、在controller类定义分组注解，不同的组生成不同的html文件
2、每个controller生成一个html，统一index.html来索引

**Comment by ayz6uem** [comment]
感谢反馈，正在考虑

**Comment by ayz6uem** [comment]
可以使用@group groupName
默认groupName 为index
