### ISSUE TITLE
扫描到非 API 接口的 Controller

### ISSUE THREAD

**Issue by hongquan66** [apigcc/apigcc#20]
hi，非常感谢作者提供这款工具，使用非常方便，也省去很多与移动端沟通的时间。作为一个非侵入式框架能够达到这样的效果已经非常不错了
使用之后发现有个问题，项目中接口和后台是整合在一起的，所有有些 `Controller` 用于处理后台的业务逻辑，而生成的接口文档会将所有的 `Controller` 中的方法全部扫描出来
是否可以增加配置项，来指定生成某些规则的 `Controller`
例如 `RequestMapping` 以 `api` 开头的 `Controller` 才是需要生成的接口
那在插件中使用自定义配置 <url>api/**</url> 类似的效果，希望作者考虑

**Comment by ayz6uem** [comment]
好的，感谢反馈

**Comment by ayz6uem** [comment]
可以使用@group groupName
默认groupName为index
