### ISSUE TITLE
添加@ignore 时，接口无法识别，post请求的接口，返回参数没有解析出来

### ISSUE THREAD

**Issue by helongjun** [apigcc/apigcc#21]
1.使用@PostMapping 注解的接口，返回对象无法解析;
2.使用@ignore unit.adminAccount 过滤属性时，接口没有解析；

**Comment by ayz6uem** [comment]
请帖一下你的代码

**Comment by ayz6uem** [comment]
要确保能读到源码，可以通过配置 denpendency的方式

**Comment by helongjun** [comment]
`/**
     * 新增组织机构
     *
     * @param unit    组织机构信息
     * @param request
     * @return
     * @ignore unit.createUser
     */
    @PostMapping("/createUnit")
    public ResultData createUnitInfo(@RequestBody @Valid Unit unit, HttpServletRequest request) {
        return unitService.createUnit(unit, UserUtil.getUser(request));
    }`

maven:
`
			<plugin>
				<groupId>com.github.apiggs</groupId>
				<artifactId>apiggs-maven-plugin</artifactId>
				<version>1.6</version>
				<executions>
					<execution>
						<phase>compile</phase>
						<goals>
							<goal>apiggs</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<production>api</production>
					<out>src/main/resources/static</out>
				</configuration>
			</plugin>`

**Comment by ayz6uem** [comment]
1. ResultData 是公共包里的么？
在maven中配置ResultData源码位置
```
<configuration>
   <dependency>ResultData源码位置</dependency>
</configuration>
```
2. @ignore 加在方法上时，该方法会忽略；请加在Unit的字段createUser的注释中

**Comment by helongjun** [comment]
是的，公共包里面的类无法解析吗

**Comment by ayz6uem** [comment]
由于不是运行时，无法找到公共包在哪，需要手动配置公共包的位置

**Comment by helongjun** [comment]
如何配置位置

**Comment by ayz6uem** [comment]
```
<configuration>
   <dependency>ResultData源码位置</dependency>
</configuration>
```

**Comment by helongjun** [comment]
好的，谢谢您
