### ISSUE TITLE
泛型无法解析

### ISSUE THREAD

**Issue by caoshengchong** [apigcc/apigcc#23]
![page-1](https://user-images.githubusercontent.com/19544021/58680511-9df82b80-839a-11e9-9734-98be00482506.jpg)
![page-2](https://user-images.githubusercontent.com/19544021/58680514-a05a8580-839a-11e9-8c1c-bdf2ce91c4bb.jpg)
![page-3](https://user-images.githubusercontent.com/19544021/58680516-a2244900-839a-11e9-988b-c32d4d7cc46d.jpg)

**Comment by ayz6uem** [comment]
感谢反馈，最近在重新梳理工具，会修复这个问题

**Comment by ayz6uem** [comment]
已支持
