### ISSUE TITLE
如何确定response status？

### ISSUE THREAD

**Issue by horryw** [apigcc/apigcc#26]
例如一个PUT方法，response body没有内容，我打算响应204，但文档中却并没有生成该说明，应该用什么参数来进行配置呢？

**Comment by horryw** [comment]
就类似@index可以调整文档顺序，这类参数都有哪些呢？在哪里可以找到说明文档呢？

**Comment by ayz6uem** [comment]
目前没有解析ResponseCode，文档中不会生成。可以先在接口说明中标注。
说明文档正在重新整理
