### ISSUE TITLE
响应内容不显示

### ISSUE THREAD

**Issue by CtrlAndZ** [apigcc/apigcc#33]
使用的maven插件，1.6的版本，文档生成成功了，但是只有请求内容，没有响应内容，返回使用的对象使用的demo中的HelloDto

**Comment by CtrlAndZ** [comment]
我明白了，是我把HelloDto放在基础模块下，然后控制器这边不在一个模块里面，只是依赖了基础模块，那我要怎么做才能让响应内容出现呢

**Comment by ayz6uem** [comment]
```
<plugin>
    <groupId>com.github.apiggs</groupId>
    <artifactId>apiggs-maven-plugin</artifactId>
    <version><!-- 替换为上方版本号 --></version>
    <executions>
        <execution>
            <phase>compile</phase>
            <goals>
                <goal>apiggs</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <!-- options in there -->
        <dependency></dependency>
    </configuration>
</plugin>
```

configuration中 增加 dependency，指向基础模块目录

**Comment by CtrlAndZ** [comment]
> ```
> <plugin>
>     <groupId>com.github.apiggs</groupId>
>     <artifactId>apiggs-maven-plugin</artifactId>
>     <version></version>
>     <executions>
>         <execution>
>             <phase>compile</phase>
>             <goals>
>                 <goal>apiggs</goal>
>             </goals>
>         </execution>
>     </executions>
>     <configuration>
>         
>         <dependency></dependency>
>     </configuration>
> </plugin>
> ```
> 
> configuration中 增加 dependency，指向基础模块目录

解决了，感谢
